name: test_pull_request
on:
  pull_request:
    paths:
      - test/**

defaults: 
  run:
    working-directory: test

jobs:
  build:
    name: test workflow
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Run hello world
        run: |
          python helloworld.py